# Generated by Django 5.0.4 on 2024-06-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_a', 'Parking A'), ('parking_b', 'Parking B')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('active', 'Active')], default='active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete'), ('create', 'Create')], max_length=10),
        ),
    ]
