# Generated by Django 5.0.4 on 2024-06-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
