# Generated by Django 5.0.4 on 2024-06-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_worker_created_at_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('broke', 'Broke'), ('unavailable', 'Unavailable'), ('rented', 'Rented')], default='available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_b', 'Parking B'), ('parking_a', 'Parking A')], max_length=50, null=True),
        ),
    ]
