# Generated by Django 5.0.4 on 2024-06-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_alter_reservation_car_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='car-pictures/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='problems_picture',
            field=models.ImageField(blank=True, null=True, upload_to='car-pictures/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tyoe-pictures/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('active', 'Active')], default='active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='worker-profile/'),
        ),
    ]
